Melhorando issue template
PHPRio/cpf pull request #165
Opened 2023-03-15 21:31 UTC by CViniciusSDias

Deixando mais claro que o que deve ser usado para a parte de "Palestrante" é o **link**, não apenas o número.

Transformando os itens no final do template em uma lista.

2023-03-15 21:31 UTC, CViniciusSDias commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados do palestrante)
```suggestion
Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
```

2023-03-16 10:25 UTC, vitormattos requested changes

2023-03-16 10:25 UTC, vitormattos commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
O número já basta se a pessoa colocar com # antes, aí vira link para a issue.

Talvez vale um bloco de comentário:
```suggestion
<!--
!!! ATENÇÃO!!! Este é um bloco de comentário, isto não vai aparecer quando você criar a issue. Comentários em markdown são iguais comentários em HTML.

Observe que é um link em markdown, então entre os ( parêntesis ) coloque ou o link para a issue que você abriu com os teus dados de palestrante ou colocando #<numeroDaIssue> pois quando prefixa o número de uma issue ou pull request, o GitHub interpreta como link.
-->
Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
```

Ou até mesmo dividir este bloco de comentário em outras partes deste template.

2023-03-16 16:50 UTC, lhsazevedo commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
Acho que, nesse caso específico, só o número não basta:

`Palestrante: [**Nome Completo**](#164)`
Palestrante: [**Nome Completo**](#164)

`Palestrante: [**Nome Completo**](https://github.com/PHPRio/CFP/issues/164)`
Palestrante: [**Nome Completo**](https://github.com/PHPRio/CFP/issues/164)

2023-03-16 16:51 UTC, vitormattos commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
Ter exemplo é uma boa também, ajuda um pouco mais a resolver os problemas.

2023-03-16 16:59 UTC, lhsazevedo commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
Podemos criar um comentário único no final do template com um exemplo completo preenchido corretamente

2023-03-16 18:26 UTC, vitormattos commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
Talvez:

```
link da issue que você criou com os dados de palestrante
```

2023-03-16 18:55 UTC, lhsazevedo submitted a review, later dismissed
Parece ótimo pra mim.

Adicionei nesse review as sugestões que chegamos a conclusão no review do @vitormattos. Prefere alterar esse ou deixar para um PR seguinte?

2023-03-16 18:55 UTC, lhsazevedo commented on .github/issue_template.md
> +Palestrante: [**Nome Completo**](link da issue com dados de palestrante)
```suggestion
Palestrante: [**Nome Completo**](link da issue que você criou com seus dados de palestrante)
```

2023-03-16 18:55 UTC, lhsazevedo commented on .github/issue_template.md
> +- [GitHub](link para repositório do GitHub com exemplos (opcional))
Que tal adicionarmos um exemplo dentro de um comentário aqui no final do arquivo?

```suggestion
- [GitHub](link para repositório do GitHub com exemplos (opcional))

<!-- Exemplo:

Título: **Como o PHP funciona na Web: uma breve história do tempo**
Palavras-chave: `php`, `web`
Nível: **básico**
Palestrante: [**Vinicius Dias**](https://github.com/PHPRio/CFP/issues/38)
Descrição da palestra:
> PHP é uma linguagem famosa pelo seu uso na Web, mas como o PHP realmente funciona na Web? Nessa palestra nós vamos entender como o PHP era executado antigamente e como nós podemos ter o PHP rodando na Web nos dias de hoje.

- [Slides](https://speakerdeck.com/cviniciussdias/como-o-php-funciona-na-web-uma-breve-historia-do-tempo)
- [GitHub](https://github.com/CViniciusSDias/talk-php-na-web)

-->

```

2023-03-20 21:13 UTC, lhsazevedo approved these changes

2023-03-20 23:03 UTC, merged